name: shrine_mvc
description: The Shrine Sample App using the MVC design pattern.

version: 0.6.0

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  mvc_application: ^1.1.0
   # path: ../../packages/mvc_application

  intl: ^0.15.8

  scoped_model: ^1.0.1

  path_provider: 


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flappy_translator:


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/diamond.png
    - assets/slanted_menu.png
    - assets/0-0.jpg
    - assets/1-0.jpg
    - assets/2-0.jpg
    - assets/3-0.jpg
    - assets/4-0.jpg
    - assets/5-0.jpg
    - assets/6-0.jpg
    - assets/7-0.jpg
    - assets/8-0.jpg
    - assets/9-0.jpg
    - assets/10-0.jpg
    - assets/11-0.jpg
    - assets/12-0.jpg
    - assets/13-0.jpg
    - assets/14-0.jpg
    - assets/15-0.jpg
    - assets/16-0.jpg
    - assets/17-0.jpg
    - assets/18-0.jpg
    - assets/19-0.jpg
    - assets/20-0.jpg
    - assets/21-0.jpg
    - assets/22-0.jpg
    - assets/23-0.jpg
    - assets/24-0.jpg
    - assets/25-0.jpg
    - assets/26-0.jpg
    - assets/27-0.jpg
    - assets/28-0.jpg
    - assets/29-0.jpg
    - assets/30-0.jpg
    - assets/31-0.jpg
    - assets/32-0.jpg
    - assets/33-0.jpg
    - assets/34-0.jpg
    - assets/35-0.jpg
    - assets/36-0.jpg
    - assets/37-0.jpg
  
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
