import 'dart:async' show Future;

import 'dart:io' show Directory, File, FileMode;

import 'package:flutter/material.dart'
    show BuildContext, Locale, Localizations, LocalizationsDelegate, Text;

import 'package:path_provider/path_provider.dart'
    show getApplicationDocumentsDirectory;

/// This class is generated by flappy_translator package
/// You should never change something directly in this file but, instead, generate new file when needed with the package
class I18n {
  String get shrine => s("Shrine");

  String get username => s("Username");

  String get password => s("Password");

  String get cancel => s("Cancel");

  String get next => s("Next");

  String get menu => s("Menu");

  String get all => s("All");

  String get accessories => s("Accessories");

  String get clothing => s("Clothing");

  String get home => s("Home");

  I18n(Locale locale) {
    this._locale = locale;
    _localizedValues = null;
  }

  Locale _locale;

  static I18nDelegate _delegate = I18nDelegate();

  static Map<String, String> _localizedValues;

  //"Shrine": "Shrine",

  static Map<String, String> _enValues = {
    "SHRINE": "SHRINE",
    "Username": "Username",
    "Password": "Password",
    "Cancel": "Cancel",
    "Next": "Next",
    "Menu": "Menu",
    "ALL": "ALL",
    "ACCESSORIES": "ACCESSORIES",
    "CLOTHING": "CLOTHING",
    "HOME": "Home",
    "Vagabond sack": "Vagabond sack",
    "Stella sunglasses": "Stella sunglasses",
    "Whitney belt": "Whitney belt",
    "Garden strand": "Garden strand",
    "Strut earrings": "Strut earrings",
    "Varsity socks": "Varsity socks",
    "Weave keyring": "Weave keyring",
    "Gatsby hat": "Gatsby hat",
    "Shrug bag": "Shrug bag",
    "Gilt desk trio": "Gilt desk trio",
    "Copper wire rack": "Copper wire rack",
    "Soothe ceramic set": "Soothe ceramic set",
    "Hurrahs tea set": "Hurrahs tea set",
    "Blue stone mug": "Blue stone mug",
    "Rainwater tray": "Rainwater tray",
    "Chambray napkins": "Chambray napkins",
    "Succulent planters": "Succulent planters",
    "Quartet table": "Quartet table",
    "Kitchen quattro": "Kitchen quattro",
    "Clay sweater": "Clay sweater",
    "Sea tunic": "Sea tunic",
    "Plaster tunic": "Plaster tunic",
    "White pinstripe shirt": "White pinstripe shirt",
    "Chambray shirt": "Chambray shirt",
    "Seabreeze sweater": "Seabreeze sweater",
    "Gentry jacket": "Gentry jacket",
    "Navy trousers": "Navy trousers",
    "Walter henley (white)": "Walter henley (white)",
    "Surf and perf shirt": "Surf and perf shirt",
    "Ginger scarf": "Ginger scarf",
    "Ramona crossover": "Ramona crossover",
    "Chambray shirt": "Chambray shirt",
    "Classic white collar": "Classic white collar",
    "Cerise scallop tee": "Cerise scallop tee",
    "Shoulder rolls tee": "Shoulder rolls tee",
    "Grey slouch tank": "Grey slouch tank",
    "Sunshirt dress": "Sunshirt dress",
    "Fine lines tee": "Fine lines tee",
  };

  static Map<String, String> _frValues = {
    "Shrine": "Tombeau",
    "SHRINE": "TOMBEAU",
    "Username": "nom d'utilisateur",
    "Password": "mot de passe",
    "Cancel": "annuler",
    "Next": "suivant",
    "Menu": "Menu",
    "ALL": "Tout",
    "ACCESSORIES": "ACCESSOIRES",
    "CLOTHING": "Vêtements",
    "HOME": "ACCUEIL",
    "Vagabond sack": "Sac vagabond",
    "Stella sunglasses": "Stella des lunettes de soleil",
    "Whitney belt": "Whitney ceinture",
    "Garden strand": "Jardinet",
    "Strut earrings": "Boucles d'oreilles strut",
    "Varsity socks": "Chaussettes Varsity",
    "Weave keyring": "Tisser porte-clés",
    "Gatsby hat": "Gatsby a",
    "Shrug bag": "Sac à dos",
    "Gilt desk trio": "Trio bureau doré",
    "Copper wire rack": "Grille en cuivre",
    "Soothe ceramic set": "Apaiser ensemble de céramique",
    "Hurrahs tea set": "Service à thé Hurrahs",
    "Blue stone mug": "Mug en pierre bleue",
    "Rainwater tray": "Bac à eau de pluie",
    "Chambray napkins": "Serviettes Chambray",
    "Succulent planters": "Planteurs succulents",
    "Quartet table": "Table de quartet",
    "Kitchen quattro": "Cuisine quattro",
    "Clay sweater": "Pull en terre cuite",
    "Sea tunic": "Tunique de mer",
    "Plaster tunic": "Tunique en plâtre",
    "White pinstripe shirt": "Chemise blanche à fines rayures",
    "Chambray shirt": "Chemise en chambray",
    "Seabreeze sweater": "Pull Seabreeze",
    "Gentry jacket": "Veste de gentry",
    "Navy trousers": "Pantalon bleu marine",
    "Walter henley (white)": "Walter henley (blanc)",
    "Surf and perf shirt": "Tee shirt surf et perf",
    "Ginger scarf": "Écharpe gingembre",
    "Ramona crossover": "Croisement de Ramona",
    "Chambray shirt": "Chemise en chambray",
    "Classic white collar": "Col blanc classique",
    "Cerise scallop tee": "Tee-shirt cerise",
    "Shoulder rolls tee": "Té d'épaule",
    "Grey slouch tank": "Réservoir gris",
    "Sunshirt dress": "Robe Sunshirt",
    "Fine lines tee": "Tee-shirt lignes fines",
  };

  static Map<String, String> _esValues = {
    "Shrine": "Santuario",
    "SHRINE": "SANTUARIO",
    "Username": "nombre de usuario",
    "Password": "contraseña",
    "Cancel": "cancelar",
    "Next": "próximo",
    "Menu": "Menú",
    "ALL": "TODOS",
    "ACCESSORIES": "ACCESORIOS",
    "CLOTHING": "ROPA",
    "HOME": "CASA",
    "Vagabond sack": "Saco de vagabundo",
    "Stella sunglasses": "Gafas de sol Stella",
    "Whitney belt": "Cinturón Whitney",
    "Garden strand": "Filamento del jardín",
    "Strut earrings": "Pendientes de puntal",
    "Varsity socks": "Calcetines universitarios",
    "Weave keyring": "Llavero de tejido",
    "Gatsby hat": "Gatsby tiene",
    "Shrug bag": "Bolsa de encogimiento de hombros",
    "Gilt desk trio": "Trío de escritorio dorado",
    "Copper wire rack": "Rejilla de cobre",
    "Soothe ceramic set": "Calmante conjunto de cerámica",
    "Hurrahs tea set": "Juego de té Hurrahs",
    "Blue stone mug": "Taza de piedra azul",
    "Rainwater tray": "Bandeja de agua de lluvia",
    "Chambray napkins": "Servilletas de cambray",
    "Succulent planters": "Plantadores suculentos",
    "Quartet table": "Mesa de cuarteto",
    "Kitchen quattro": "Quattro de cocina",
    "Clay sweater": "Suéter de arcilla",
    "Sea tunic": "Túnica de mar",
    "Plaster tunic": "Túnica de yeso",
    "White pinstripe shirt": "Camisa blanca a rayas",
    "Chambray shirt": "Camisa de cambray",
    "Seabreeze sweater": "Jersey Seabreeze",
    "Gentry jacket": "Chaqueta Gentry",
    "Navy trousers": "Pantalones azul marino",
    "Walter henley (white)": "Walter henley (blanco)",
    "Surf and perf shirt": "Camisa de surf y perf",
    "Ginger scarf": "Bufanda de jengibre",
    "Ramona crossover": "Crossover Ramona",
    "Chambray shirt": "Camisa de cambray",
    "Classic white collar": "Cuello blanco clásico",
    "Cerise scallop tee": "Camiseta de vieira de Cerise",
    "Shoulder rolls tee": "Hombro rollos tee",
    "Grey slouch tank": "Tanque gris holgado",
    "Sunshirt dress": "Vestido camisero",
    "Fine lines tee": "Tee de líneas finas",
  };

  static Map<String, Map<String, String>> _allValues = {
    "en": _enValues,
    "fr": _frValues,
    "es": _esValues,
  };

  static I18n of(BuildContext context) {
    return Localizations.of<I18n>(context, I18n);
  }

  static String s(String key) {
    if (key == null) {
      return 'null';
    }
//    return _localizedValues == null ? key : _localizedValues[key] ?? key;

    if (_localizedValues == null) {
      return key;
    }
    String value = _localizedValues[key];
    if (value == null) {
      if (_I18nFile.inIDE) _I18nFile.save(key);
      value = key;
    }
    return value;
  }

  static Text t(String key) {
    return Text(s(key));
  }

  static Future<I18n> load(Locale locale) async {
    I18n translations = new I18n(locale);
    _localizedValues =
        _delegate.isSupported(locale) ? _allValues[locale.languageCode] : _allValues["en"];
    return translations;
  }

  get currentLanguage => _locale.languageCode;
}

class I18nDelegate extends LocalizationsDelegate<I18n> {
  const I18nDelegate();

  @override
  bool isSupported(Locale locale) =>
      ['en', 'fr', 'es'].contains(locale.languageCode);

  @override
  Future<I18n> load(Locale locale) => I18n.load(locale);

  @override
  bool shouldReload(I18nDelegate old) => false;
}

class _I18nFile {
  static String _fileName = "i18n.csv";
  static File _file;

  static Future<File> file() async {
    if (_file == null) {
      final Directory directory = await getApplicationDocumentsDirectory();
      _file = File('${directory.path}/$_fileName');
    }
    return _file;
  }

  static Future<String> read() async {
    String text;
    try {
      final File f = await file();
      text = await f.readAsString();
    } catch (ex) {
      text = "";
    }
    return text;
  }

  static Future<bool> save(String text) async {
    bool save;
    try {
      File f = await file();
      f = await f.writeAsString(text, mode: FileMode.append, flush: true);
      save = f is File;
    } catch (ex) {
      save = false;
    }
    return save;
  }

  /// Determines if running in an IDE or in production.
  static bool get inIDE {
    var inDebugMode = false;
    // assert is removed in production.
    assert(inDebugMode = true);
    return inDebugMode;
  }
}
